cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.CartSummaryView.as_view(), name='cart_summary'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('update/<int:product_id>/', views.CartUpdateView.as_view(), name='cart_update'),
]

djangoProject9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10, widget=forms.NumberInput(attrs={'class': 'form-control',
                                                                                             'placeholder': 'تعداد محصول..'}), label='')

cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .cart import Cart
from shop.models import Product
from .forms import CartAddForm


class CartSummaryView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'cart/cart_summary.html', {'cart': cart})


class CartAddView(LoginRequiredMixin, View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, pk=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('shop:detail', product.id)


class CartRemoveView(LoginRequiredMixin, View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, pk=product_id)
        cart.remove(product)
        return redirect('cart:cart_summary')


class CartUpdateView(LoginRequiredMixin, View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, pk=product_id)
        quantity_change = request.POST.get('quantity_change')
        new_quantity = request.POST.get('quantity')

        if quantity_change is not None:
            try:
                quantity_change = int(quantity_change)
            except ValueError:
                quantity_change = 0

            current_quantity = cart.cart.get(str(product.id), {}).get('quantity', 1)
            new_quantity = max(1, current_quantity + quantity_change)

        elif new_quantity is not None:
            try:
                new_quantity = int(new_quantity)
            except ValueError:
                new_quantity = 1

            new_quantity = max(1, new_quantity)

        else:
            new_quantity = 1

        cart.update(product, new_quantity)
        return redirect('cart:cart_summary')

cart/templates/cart/cart_summary.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <header class="bg-secondary py-3">
        {% include 'inc/messages.html' %}
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">سبد خرید شما</h1>
                <p class="lead fw-normal text-white-50 mb-0">محصولات باکیفیت و قیمت بصرفه</p>
            </div>
        </div>
    </header>

    <div class="container mt-5">
        <div class="col-md-12">
            {% for item in cart %}
                <div class="card mb-3">
                    <img src="{{ item.product.picture.url }}" class="card-img-top" style="width: 100px; height: 100px;" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.product }}</h5>
                    <br>
                    <br>
                        <form action="{% url 'cart:cart_update' item.product.id %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <input type="hidden" name="quantity_change" value="-1">
                            <button type="submit" class="btn btn-outline-secondary" {% if item.quantity == 1 %} disabled{% endif %}>-</button>
                        </form>
                            <h6 class="card-text d-inline-block"> [ {{ item.quantity }} ] </h6>
                        <form action="{% url 'cart:cart_update' item.product.id %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <input type="hidden" name="quantity_change" value="1">
                            <button type="submit" class="btn btn-outline-secondary" {% if item.quantity == 10 %} disabled{% endif %}>+</button>
                        </form>
                        <br>
                        <br>


                        {% if item.product.is_sale %}
                        	<p class="card-text"><small class="text-body-secondary">قیمت : <strike>{{ item.price|intcomma }}</strike> تومان</small></p>
                            <p class="card-text"><small class="text-body-secondary">تخفیف : {{ item.sale_price|intcomma }}تومان</small></p>
                        {% else %}
                            <p class="card-text"><small class="text-body-secondary">قیمت : {{ item.price|intcomma }} تومان</small></p>
                            <p class="card-text"><small class="text-body-secondary">تخفیف : 0 </small></p>
                        {% endif %}

                        <hr>
                        <h6 class="card-text"><small class="text-body-secondary">جمع کل : {{ item.total_price|intcomma }} تومان</small></h6>
                        <a class="btn btn-light" href="{% url 'cart:cart_remove' item.product.id %}">حذف</a>
                    </div>
                </div>
            {% endfor %}

            <div class="card text-sm-center">
                <div class="card-header">
                    برو به صفحه پرداخت.
                </div>
                <div class="card-body">
                    <h5 class="card-title"> مبلغ قابل پرداخت : {{ cart.get_total_price|intcomma }} تومان </h5>
                    <p class="card-text"></p>
                    <a href="#" class="btn btn-primary">پرداخت</a>
                </div>
                <div class="card-footer text-body-secondary">
                </div>
            </div>
        </div>
    </div>
{% endblock %}