cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.CartSummaryView.as_view(), name='cart_summary'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('update/<int:product_id>/', views.CartUpdateView.as_view(), name='cart_update'),
]

djangoProject9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('product/<int:pk>/', views.DetailProductView.as_view(), name='detail'),
    path('category/', views.CategoryView.as_view(), name='category'),
    path('category/<str:cat>/', views.CatProductView.as_view(), name='category_product'),
]

shop/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator



class Category(models.Model):
    name = models.CharField(max_length=50)
    picture = models.ImageField(upload_to='Category/', default='Category/default.jpg')

    def __str__(self):
        return self.name


class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    password = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name} - {self.last_name}'


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500, default='', blank=True, null=True)
    price = models.DecimalField(default=0, decimal_places=0, max_digits=12)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    picture = models.ImageField(upload_to='products/', blank=True, null=True)
    star = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    is_sale = models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0, decimal_places=0, max_digits=12)

    def __str__(self):
        return self.name


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length=400, default='', blank=True)
    phone = models.CharField(max_length=20, blank=True)
    data = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.product

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib import messages
from cart.forms import CartAddForm
from .models import Product, Category


class IndexView(View):
    def get(self, request):
        products = Product.objects.all()
        return render(request, 'shop/index.html', {'products': products})


class AboutView(View):
    def get(self, request):
        return render(request, 'shop/about.html')


class DetailProductView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = CartAddForm()
        return render(request, 'shop/detail_product.html', {"product": product, 'form': form})


class CategoryView(View):
    def get(self, request):
        category = Category.objects.all()
        return render(request, 'shop/category.html', {"category": category})


class CatProductView(View):
    def get(self, request, cat):
        cat = cat.replace('-', ' ')
        try:
            category = Category.objects.get(name=cat)
            products = Product.objects.filter(category=category)
            return render(request, 'shop/product.html', {'products': products, 'category': category})
        except:
            messages.error(request, 'دسته بندی وجود ندارد')
            return redirect('shop:home')

shop/templates/shop/category.html
{% extends 'base.html' %}

{% block content %}
{% load humanize %}

        <!-- Header-->
        <header class="bg-secondary py-3">
        {% include 'inc/messages.html' %}
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder mb-4">دسته بندی محصولات</h1>
                    <p class="lead fw-normal text-white-50 mb-0">تنوع محصولات و کیفیت عالی</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for cat in category %}
                        <div class="col mb-3">
                            <div class="card h-100">
                               <div class="card-body">
                                   <h5 class="card-title text-center"><img class="align-items-center" src="{{ cat.picture.url }}" style="width: 100px; height: 70px;" alt=""></h5>
                                   <h5 class="card-title text-center"><a style="text-decoration: none;" href="{% url 'shop:category_product' cat.name %}">{{ cat.name }}</a></h5>
                                <p class="card-text"></p>
                               </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    <br>
    <br>
    <br>


{% endblock %}

shop/templates/shop/detail_product.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <br><br><br><br>
    <div class="container mt-5">
    <div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ product.picture.url }}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description }}</p>
            {% if product.is_sale %}
            	 <p class="card-text"><small class="text-body-secondary">قیمت💰 : <strike>{{ product.price | intcomma }} </strike>تومان - {{ product.sale_price | intcomma }} تومان</small></p>
            {% else %}
                <p class="card-text"><small class="text-body-secondary">قیمت💰 : {{ product.price | intcomma }} تومان</small></p>
            {% endif %}
          <br>
          <br>
          <br>

          <form action="{% url 'cart:cart_add' product.id %}" method="post" class="col-md-3">
              {% csrf_token %}
              {{ form }}<br>
              <button class="add-to-cart btn btn-secondary" >اضافه کردن به سبد خرید</button>
          </form>
          <br>
          <a href="{% url 'shop:home' %}" class="btn btn-secondary">بروبه صفحه اصلی </a>
      </div>
    </div>
  </div>
</div>
</div>
        <br><br><br><br><br><br><br><br><br><br><br><br>



{% endblock %}

shop/templates/shop/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load humanize %}

        <!-- Header-->
        <header class="bg-secondary py-3" >
        {% include 'inc/messages.html' %}
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
{#                    <img class="mt-0" style="height: 100%; width: 100%;" src="{% static 'img/1.jpg' %}" alt="">#}
                    <h1 class="display-4 fw-bolder"> G U Z A L -<span style="color: #38c281">Shop</span></h1>
                    <p class="lead fw-normal text-white-50 mb-0">بهترین فروشگاه آنلاین در کشور</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5" >
            <div class="container px-4 px-lg-5 mt-5">
            <center class="mb-5"><h2>تمام محصولات</h2></center>
                <hr>
                <br>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                    {% for product in products %}
                        {% if product.is_sale %}
                            <div class="col mb-5">
                        <div class="card h-100" style="background-color: #f3f2f6">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">تخفیف ویژه</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.picture.url }}"  alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name| truncatewords:5 }}</h5>
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                    {% with ''|center:product.star as range  %}
                                    	{% for _ in range %}
                                            <div class="bi-star-fill"></div>
                                        {% endfor %}
                                    {% endwith %}
                                    </div>
                                    <!-- Product price-->
                                     <strike>{{ product.price | intcomma }}  تومان</strike><br>
                                    {{ product.sale_price | intcomma }} تومان
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'shop:detail' product.id %}">برو به صفحه محصول</a></div>
                            </div>
                        </div>
                    </div>
                        {% else %}
                             <div class="col mb-5">
                        <div class="card h-100" style="background-color: #f3f2f6">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.picture.url }}"  alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name| truncatewords:8 }}</h5>
                                     <div class="d-flex justify-content-center small text-warning mb-2">
                                    {% with ''|center:product.star as range  %}
                                    	{% for _ in range %}
                                            <div class="bi-star-fill"></div>
                                        {% endfor %}
                                    {% endwith %}
                                    </div>
                                    <!-- Product price-->
                                    {{ product.price | intcomma }} تومان
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'shop:detail' product.id %}">برو به صفحه محصول</a></div>
                            </div>
                        </div>
                    </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </section>

{% endblock %}

shop/templates/shop/product.html
{% extends 'base.html' %}

{% block content %}
{% load humanize %}

        <!-- Header-->
        <header class="bg-secondary py-3">
        {% include 'inc/messages.html' %}
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder mb-4">{{ category.name}}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">تنوع محصولات و کیفیت عالی</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <section class="py-5">
                <div class="container px-4 px-lg-5 mt-5">
                    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                        {% for product in products %}
                            {% if product.is_sale %}
                                <div class="col mb-5">
                        <div class="card h-100">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">تخفیف ویژه</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.picture.url }}"  alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                    {% with ''|center:product.star as range  %}
                                    	{% for _ in range %}
                                            <div class="bi-star-fill"></div>
                                        {% endfor %}
                                    {% endwith %}
                                    </div>
                                    <!-- Product price-->
                                     <strike>{{ product.price | intcomma }}  تومان</strike><br>
                                    {{ product.sale_price | intcomma }} تومان
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'shop:detail' product.id %}">برو به صفحه محصول</a></div>
                            </div>
                        </div>
                    </div>
                            {% else %}
                                <div class="col mb-5 ">
                                    <div class="card h-100"  style="background-color: #ece9ef">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.picture.url }}"  alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                     <div class="d-flex justify-content-center small text-warning mb-2">
                                    {% with ''|center:product.star as range  %}
                                    	{% for _ in range %}
                                            <div class="bi-star-fill"></div>
                                        {% endfor %}
                                    {% endwith %}
                                    </div>
                                    <!-- Product price-->
                                    {{ product.price | intcomma }} تومان
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'shop:detail' product.id %}">برو به صفحه محصول</a></div>
                            </div>
                        </div>
                                 </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </section>
        </section>

{% endblock %}