accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.CartSummaryView.as_view(), name='cart_summary'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('update/<int:product_id>/', views.CartUpdateView.as_view(), name='cart_update'),
]

djangoProject9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('product/<int:pk>/', views.DetailProductView.as_view(), name='detail'),
    path('category/', views.CategoryView.as_view(), name='category'),
    path('category/<str:cat>/', views.CatProductView.as_view(), name='category_product'),
]

templates/inc/messages.html
{% if messages %}
	{% for message in messages %}
		<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
           {{ message }}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
	{% endfor %}
	
{% endif %} 

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
                
     <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <button class="btn btn- dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.is_authenticated %}
              	<i class="material-icons">person_outline</i>{{ user.full_name }} 
              {% else %}
                  <i class="material-icons ">devices</i>ورود | ثبت نام  
              {% endif %} 
          </button>
          <ul class="dropdown-menu dropdown-menu-">
               {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'accounts:user_logout' %}">خروج</a></li>
               {% else %}
                    <li><a class="dropdown-item" href="{% url 'accounts:user_login' %}">ورود</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:user_register' %}">ثبت نام</a></li>
              {% endif %}
          </ul>
        </li>
      </ul>
    </div>
    
    
    
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'shop:home' %}">G U Z A L<span style="color: #38c281">-Shop</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                
                
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">خانه</a></li>
                        <li class="nav-item"><a class="nav-link" href="{%  url 'shop:about' %}">درباره ما</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:category'  %}">دسته بندی</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="{% url 'shop:home' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">فروشگاه</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'shop:home' %}">همه محصولات</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'shop:category'  %}">دسته بندی</a></li>
                                <li><a class="dropdown-item" href="#!">محصولات جدید</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <a href="{% url 'cart:cart_summary' %}" class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            سبد خرید
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length }}</span>
                        </a>
                    </form>
                </div>
            </div>
        </nav>